import { Suspense } from "react"
import { notFound } from "next/navigation"
import Link from "next/link"
import { TrendingUp, ArrowRight, Building2, Calendar, MapPin, BarChart3, Shield } from "lucide-react"

interface ValuationData {
  id: number
  firstName: string
  agencyName: string | null
  toolUsed: string
  estimatedValue: string | null
  valuationSummary: string | null
  createdAt: string
  lowOffer: string | null
  highOffer: string | null
  state: string | null
  annualRevenue: string | null
  retentionRate: string | null
  bookType: string | null
  qvLow: string | null
  qvHigh: string | null
  qvRevenue: string | null
}

function fmt(n: string | null | undefined) {
  if (!n) return "—"
  const num = parseFloat(n)
  if (isNaN(num)) return "—"
  if (num >= 1_000_000) return `$${(num / 1_000_000).toFixed(2)}M`
  if (num >= 1_000)     return `$${(num / 1_000).toFixed(0)}K`
  return `$${num.toFixed(0)}`
}

async function getValuation(id: string): Promise<ValuationData | null> {
  const base = process.env.NEXT_PUBLIC_BASE_URL
    ?? (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "http://localhost:3000")
  try {
    const res = await fetch(`${base}/api/valuations/${id}`, { next: { revalidate: 3600 } })
    if (!res.ok) return null
    return res.json()
  } catch {
    return null
  }
}

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const v = await getValuation(id)
  if (!v) return { title: "Valuation Not Found — Agency Appraiser" }
  return {
    title: `Agency Valuation Report — Agency Appraiser`,
    description: v.agencyName
      ? `See the estimated value for ${v.agencyName} — generated by Agency Appraiser.`
      : "An insurance agency valuation report generated by Agency Appraiser.",
    openGraph: {
      title: `Agency Valuation — ${v.agencyName ?? "Independent Agency"}`,
      description: v.estimatedValue
        ? `Estimated value: ${fmt(v.estimatedValue)}. See the full report.`
        : "View the full agency valuation report.",
    },
  }
}

export default async function ValuationSharePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const v = await getValuation(id)
  if (!v) notFound()

  const low  = v.lowOffer  ?? v.qvLow
  const high = v.highOffer ?? v.qvHigh
  const rev  = v.annualRevenue ?? v.qvRevenue
  const date = new Date(v.createdAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })

  const toolLabel =
    v.toolUsed?.includes("full")  ? "Full Valuation"  :
    v.toolUsed?.includes("quick") ? "Quick Valuation" :
    v.toolUsed?.includes("quiz")  ? "Value Quiz"      : "Agency Valuation"

  return (
    <div className="min-h-screen bg-background">
      {/* Top bar */}
      <header className="border-b border-border bg-card/60 px-4 py-3 backdrop-blur-sm">
        <div className="mx-auto flex max-w-3xl items-center justify-between">
          <Link href="/" className="flex items-center gap-2 text-sm font-bold text-foreground">
            <div className="flex h-6 w-6 items-center justify-center rounded bg-primary">
              <TrendingUp className="h-3.5 w-3.5 text-primary-foreground" />
            </div>
            Agency Appraiser
          </Link>
          <Link
            href="/calculator"
            className="flex items-center gap-1.5 rounded-md bg-primary px-3 py-1.5 text-xs font-semibold text-primary-foreground transition-opacity hover:opacity-90"
          >
            Get Your Valuation <ArrowRight className="h-3 w-3" />
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-10 space-y-6">
        {/* Hero card */}
        <div className="rounded-2xl border border-border bg-card p-6 sm:p-8">
          {/* Label */}
          <div className="mb-5 flex items-center gap-2">
            <span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">
              {toolLabel}
            </span>
            <span className="text-xs text-muted-foreground flex items-center gap-1">
              <Calendar className="h-3 w-3" /> {date}
            </span>
          </div>

          {/* Agency name */}
          <div className="mb-6">
            <div className="flex items-center gap-2 text-muted-foreground mb-1">
              <Building2 className="h-4 w-4" />
              <span className="text-sm">{v.agencyName ?? `${v.firstName}'s Agency`}</span>
              {v.state && (
                <span className="flex items-center gap-1 text-xs text-muted-foreground/60">
                  <MapPin className="h-3 w-3" /> {v.state}
                </span>
              )}
            </div>
            <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl text-balance">
              Estimated Agency Value
            </h1>
          </div>

          {/* Value range */}
          {low && high ? (
            <div className="rounded-xl border border-primary/20 bg-primary/5 px-6 py-5 mb-6">
              <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground mb-2">Valuation Range</p>
              <div className="flex items-end gap-3 flex-wrap">
                <span className="text-4xl font-bold text-foreground sm:text-5xl font-mono">
                  {fmt(low)}
                </span>
                <span className="text-2xl text-muted-foreground mb-1">—</span>
                <span className="text-4xl font-bold text-primary sm:text-5xl font-mono">
                  {fmt(high)}
                </span>
              </div>
              {v.estimatedValue && (
                <p className="mt-2 text-sm text-muted-foreground">
                  Midpoint estimate: <span className="font-semibold text-foreground">{fmt(v.estimatedValue)}</span>
                </p>
              )}
            </div>
          ) : v.estimatedValue ? (
            <div className="rounded-xl border border-primary/20 bg-primary/5 px-6 py-5 mb-6">
              <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground mb-2">Estimated Value</p>
              <span className="text-5xl font-bold text-primary font-mono">{fmt(v.estimatedValue)}</span>
            </div>
          ) : null}

          {/* Key metrics */}
          {(rev || v.retentionRate || v.bookType) && (
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
              {rev && (
                <div className="rounded-lg border border-border bg-secondary/40 px-4 py-3">
                  <p className="text-xs text-muted-foreground mb-1">Annual Revenue</p>
                  <p className="text-lg font-bold text-foreground font-mono">{fmt(rev)}</p>
                </div>
              )}
              {v.retentionRate && (
                <div className="rounded-lg border border-border bg-secondary/40 px-4 py-3">
                  <p className="text-xs text-muted-foreground mb-1">Retention Rate</p>
                  <p className="text-lg font-bold text-foreground">{parseFloat(v.retentionRate).toFixed(0)}%</p>
                </div>
              )}
              {v.bookType && (
                <div className="rounded-lg border border-border bg-secondary/40 px-4 py-3">
                  <p className="text-xs text-muted-foreground mb-1">Book Type</p>
                  <p className="text-lg font-bold text-foreground capitalize">{v.bookType}</p>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Valuation summary */}
        {v.valuationSummary && (
          <div className="rounded-2xl border border-border bg-card p-6">
            <div className="flex items-center gap-2 mb-4">
              <BarChart3 className="h-4 w-4 text-primary" />
              <h2 className="text-sm font-semibold text-foreground">Valuation Summary</h2>
            </div>
            <p className="text-sm leading-relaxed text-muted-foreground whitespace-pre-line">
              {v.valuationSummary}
            </p>
          </div>
        )}

        {/* Disclaimer */}
        <div className="flex items-start gap-3 rounded-xl border border-border bg-secondary/20 px-4 py-4">
          <Shield className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground/60" />
          <p className="text-xs text-muted-foreground leading-relaxed">
            This valuation is an estimate based on information provided and current market data.
            It does not constitute a formal appraisal or offer to purchase. Actual transaction values
            may vary. Generated on {date} by Agency Appraiser.
          </p>
        </div>

        {/* CTA */}
        <div className="rounded-2xl border border-primary/20 bg-primary/5 p-6 text-center">
          <h2 className="text-lg font-bold text-foreground mb-2 text-balance">
            Curious what your agency is worth?
          </h2>
          <p className="text-sm text-muted-foreground mb-4">
            Get your free valuation in under 3 minutes — no obligation.
          </p>
          <div className="flex flex-col gap-2 sm:flex-row sm:justify-center">
            <Link
              href="/calculator"
              className="flex items-center justify-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground transition-opacity hover:opacity-90"
            >
              Full Valuation Calculator <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              href="/quick-value"
              className="flex items-center justify-center gap-2 rounded-lg border border-border bg-card px-5 py-2.5 text-sm font-semibold text-foreground transition-colors hover:bg-secondary"
            >
              Quick Value Estimate
            </Link>
          </div>
        </div>
      </main>

      <footer className="border-t border-border px-4 py-6 text-center">
        <p className="text-xs text-muted-foreground">
          Powered by{" "}
          <Link href="/" className="font-semibold text-foreground hover:text-primary transition-colors">
            Agency Appraiser
          </Link>
          {" "}· Independent agency valuation tools
        </p>
      </footer>
    </div>
  )
}
